# Copyright 2026 Ravi Kiran Kadaboina
# Licensed under the Apache License, Version 2.0.

"""Paper-code sync helper: render an ExtensionManifest as a human-readable
SPEC.md.

The drift problem: a protocol's preprint (paper) and its code (pydantic
models, manifest.json) are two separate artefacts that say overlapping
things about the wire format. Hand-keeping them in sync is fragile.

This module produces a `SPEC.md` from a manifest. The manifest itself
is generated from the pydantic model, so the chain is:

    pydantic *Ref class
        └─ ExtensionManifest (auto-generated by `manifest generate`)
                └─ SPEC.md (auto-generated by this module)

If the model changes, regenerating the manifest + SPEC.md is one
command. The preprint can then be edited to match. A simple CI check
("the SPEC.md committed to the repo equals the one this module would
produce right now") flags drift.

The SPEC.md is intentionally small and focused on the wire-format
table — the table is what implementers need to look at; everything
else (motivation, rationale) belongs in the preprint.
"""

from __future__ import annotations

from typing import Any

from a2a_testbed.manifest.types import ExtensionManifest


def render_spec_md(manifest: ExtensionManifest) -> str:
    """Render a manifest as a developer-facing SPEC.md.

    Output sections:
      1. Title + extension URI + version + publisher
      2. Required fields (from the JSON Schema's ``required``)
      3. Full field table (name | type | required | description)
      4. Wire artefacts (if declared)
      5. Invariants (if declared)
      6. Source-of-truth note pointing at the manifest JSON
    """
    lines: list[str] = []
    ext = manifest.extension
    lines.append(f"# {ext.name} — Wire Specification")
    lines.append("")
    lines.append(
        "> Generated from `v1/manifest.json`. "
        "Re-render after the manifest changes; "
        "do not hand-edit."
    )
    lines.append("")
    lines.append(f"- **Extension URI:** `{ext.uri}`")
    lines.append(f"- **Protocol version:** {ext.version}")
    lines.append(f"- **Manifest envelope version:** {manifest.manifest_version}")
    if ext.publisher:
        lines.append(f"- **Publisher:** {ext.publisher}")
    if ext.human_readable_spec:
        lines.append(f"- **Paper / human-readable spec:** {ext.human_readable_spec}")
    if ext.machine_readable_spec:
        lines.append(f"- **Machine-readable spec:** {ext.machine_readable_spec}")
    if ext.description:
        lines.append("")
        lines.append(ext.description)
    lines.append("")

    schema = manifest.agent_card_payload_schema or {}
    properties = schema.get("properties") or {}
    required_set = set(schema.get("required") or [])
    is_opaque = schema.get("title") == "OpaquePayload"

    lines.append("## AgentCard payload")
    lines.append("")
    if is_opaque:
        lines.append(
            "This extension declares itself by URI presence and does not "
            "constrain the AgentCard payload. Validators accept any object "
            "in the entry's `params`."
        )
    elif not properties:
        lines.append("_No `properties` defined on this manifest's payload schema._")
    else:
        if required_set:
            lines.append(
                "**Required fields:** " + ", ".join(f"`{r}`" for r in sorted(required_set)) + ""
            )
            lines.append("")

        lines.append("| Field | Type | Required | Notes |")
        lines.append("|---|---|---|---|")
        for name, prop in sorted(properties.items()):
            required = "yes" if name in required_set else "no"
            field_type = _describe_type(prop, schema)
            description = (prop.get("description") or "").replace("\n", " ").strip()
            lines.append(f"| `{name}` | {field_type} | {required} | {description} |")
    lines.append("")

    if manifest.wire_artefacts:
        lines.append("## Wire artefacts")
        lines.append("")
        for art in manifest.wire_artefacts:
            lines.append(f"### `{art.name}`")
            lines.append("")
            if art.description:
                lines.append(art.description)
                lines.append("")
            if art.endpoint_field:
                lines.append(
                    f"Delivered via `{art.method}` to the URL named in "
                    f"`agent_card_payload.{art.endpoint_field}`."
                )
                lines.append("")
        lines.append("")

    if manifest.invariants:
        lines.append("## Invariants")
        lines.append("")
        for inv in manifest.invariants:
            lines.append(f"- {inv}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "_Drift between this `SPEC.md` and the protocol's pydantic "
        "models indicates the manifest needs regenerating. CI may "
        "compare a freshly-rendered version against the committed one._"
    )
    lines.append("")

    return "\n".join(lines)


def _describe_type(prop: dict[str, Any], root: dict[str, Any]) -> str:
    """Best-effort one-token type label for the SPEC.md table."""
    if "$ref" in prop:
        ref = prop["$ref"]
        return f"`${ref.rsplit('/', 1)[-1]}`"
    t = prop.get("type")
    if isinstance(t, list):
        return " \\| ".join(t)
    if t == "array":
        items = prop.get("items") or {}
        inner = _describe_type(items, root) if items else "any"
        return f"array<{inner}>"
    if t == "object":
        addl = prop.get("additionalProperties")
        if isinstance(addl, dict):
            return f"dict<string, {_describe_type(addl, root)}>"
        return "object"
    if "enum" in prop:
        return "enum: " + ", ".join(repr(v) for v in prop["enum"])
    return t or "any"
