# Copyright 2026 Ravi Kiran Kadaboina
# Licensed under the Apache License, Version 2.0.

"""Tests for the manifest generator + dynamic AgentCard validator.

These exercise the manifest pipeline end to end against real pydantic
models from the four protocol packages, so they double as a smoke test
that the testbed can validate any A2A extension that ships a manifest.
"""

from __future__ import annotations

import json

import pytest
from pydantic import BaseModel, Field

from a2a_testbed.manifest import (
    ExtensionManifest,
    ExtensionMetadata,
    Finding,
    FindingKind,
    InMemoryManifestStore,
    LocalManifestStore,
    generate_manifest,
    manifest_url_for_uri,
    validate_agent_card,
)


# --------------------------------------------------------------------------
# Fixture pydantic model — the kind a third-party protocol author would write
# --------------------------------------------------------------------------


class FakeServiceRef(BaseModel):
    """Stand-in for a real protocol's *Ref class."""

    version: str
    endpoint: str = Field(..., description="HTTPS data plane URL")
    weight_keys: list[str] = Field(default_factory=list)


FAKE_URI = "https://example.org/fake-protocol/v1"


# --------------------------------------------------------------------------
# Generator
# --------------------------------------------------------------------------


def test_manifest_uri_url_convention():
    assert (
        manifest_url_for_uri(FAKE_URI)
        == "https://example.org/fake-protocol/v1/manifest.json"
    )


def test_generator_emits_well_formed_manifest():
    m = generate_manifest(
        extension_uri=FAKE_URI,
        name="Fake Protocol",
        version="1.0.0",
        ref_class=FakeServiceRef,
        description="test",
        publisher="Example Corp",
        invariants=["I-1: foo"],
    )
    assert m.manifest_version == "1.0.0"
    assert m.extension.uri == FAKE_URI
    assert m.extension.name == "Fake Protocol"
    assert m.invariants == ["I-1: foo"]
    # JSON Schema generated by pydantic carries the typed required fields.
    schema = m.agent_card_payload_schema
    assert "version" in schema["required"]
    assert "endpoint" in schema["required"]
    assert "weight_keys" not in schema.get("required", [])


def test_generator_accepts_dotted_path():
    m = generate_manifest(
        extension_uri=FAKE_URI,
        name="Fake",
        version="1.0.0",
        ref_class="tests.unit.test_manifest:FakeServiceRef",
    )
    assert m.extension.uri == FAKE_URI


def test_generator_resolves_wire_artefact_dotted_paths():
    m = generate_manifest(
        extension_uri=FAKE_URI,
        name="Fake",
        version="1.0.0",
        ref_class=FakeServiceRef,
        wire_artefacts=[
            {
                "name": "FakeArtefact",
                "endpoint_field": "endpoint",
                "schema": "tests.unit.test_manifest:FakeServiceRef",
            }
        ],
    )
    assert len(m.wire_artefacts) == 1
    assert m.wire_artefacts[0].json_schema["title"] == "FakeServiceRef"


def test_generator_no_ref_class_uses_opaque_payload_schema():
    """Extensions that augment runtime behavior get a permissive schema."""
    m = generate_manifest(
        extension_uri="https://example.org/runtime-only/v1",
        name="Runtime-Only Extension",
        version="1.0.0",
        # ref_class omitted
    )
    schema = m.agent_card_payload_schema
    assert schema["type"] == "object"
    assert schema["title"] == "OpaquePayload"
    assert schema["additionalProperties"] is True


@pytest.mark.asyncio
async def test_validator_accepts_any_object_against_opaque_schema():
    """OpaquePayload schema must accept arbitrary params (or absent ones)."""
    runtime_uri = "https://example.org/runtime-only/v1"
    runtime_manifest = generate_manifest(
        extension_uri=runtime_uri,
        name="Runtime-Only",
        version="1.0.0",
        # no ref_class -> OpaquePayload
    )
    store = InMemoryManifestStore({runtime_uri: runtime_manifest})

    # An arbitrary payload should validate against OpaquePayload.
    card = _card_declaring(runtime_uri, {"anything": [1, 2, 3], "else": "ok"})
    findings = await validate_agent_card(card, store=store)
    assert findings[0].kind == FindingKind.DECLARED_OK


def test_generator_rejects_non_pydantic_class():
    class NotPydantic:
        pass

    with pytest.raises(TypeError):
        generate_manifest(
            extension_uri=FAKE_URI,
            name="X",
            version="1.0.0",
            ref_class=NotPydantic,  # type: ignore[arg-type]
        )


# --------------------------------------------------------------------------
# Validator
# --------------------------------------------------------------------------


def _store_with(manifest: ExtensionManifest) -> InMemoryManifestStore:
    return InMemoryManifestStore({manifest.extension.uri: manifest})


@pytest.fixture
def fake_manifest() -> ExtensionManifest:
    return generate_manifest(
        extension_uri=FAKE_URI,
        name="Fake Protocol",
        version="1.0.0",
        ref_class=FakeServiceRef,
    )


def _card_declaring(uri: str, payload: dict | None) -> dict:
    entry: dict = {"uri": uri, "description": "Supports fake protocol."}
    if payload is not None:
        entry["params"] = payload
    return {
        "name": "test agent",
        "capabilities": {"extensions": [entry]},
    }


@pytest.mark.asyncio
async def test_validate_declared_ok(fake_manifest):
    card = _card_declaring(
        FAKE_URI,
        {"version": "1.0.0", "endpoint": "https://x/y", "weight_keys": []},
    )
    findings = await validate_agent_card(card, store=_store_with(fake_manifest))
    assert len(findings) == 1
    assert findings[0].kind == FindingKind.DECLARED_OK


@pytest.mark.asyncio
async def test_validate_declared_invalid_missing_required_field(fake_manifest):
    card = _card_declaring(
        FAKE_URI,
        {"version": "1.0.0"},  # missing 'endpoint'
    )
    findings = await validate_agent_card(card, store=_store_with(fake_manifest))
    assert len(findings) == 1
    f = findings[0]
    assert f.kind == FindingKind.DECLARED_INVALID
    assert any("endpoint" in err for err in f.schema_errors)


@pytest.mark.asyncio
async def test_validate_declared_invalid_wrong_type(fake_manifest):
    card = _card_declaring(
        FAKE_URI,
        {"version": "1.0.0", "endpoint": 42, "weight_keys": []},
    )
    findings = await validate_agent_card(card, store=_store_with(fake_manifest))
    assert findings[0].kind == FindingKind.DECLARED_INVALID
    # JSON Schema reports the type mismatch under the offending field.
    assert any("endpoint" in err for err in findings[0].schema_errors)


@pytest.mark.asyncio
async def test_validate_manifest_not_found():
    card = _card_declaring(
        FAKE_URI,
        {"version": "1.0.0", "endpoint": "https://x"},
    )
    findings = await validate_agent_card(
        card, store=InMemoryManifestStore()  # empty store
    )
    assert len(findings) == 1
    assert findings[0].kind == FindingKind.MANIFEST_NOT_FOUND


@pytest.mark.asyncio
async def test_validate_payload_missing(fake_manifest):
    card = _card_declaring(FAKE_URI, payload=None)
    findings = await validate_agent_card(card, store=_store_with(fake_manifest))
    assert findings[0].kind == FindingKind.PAYLOAD_MISSING


@pytest.mark.asyncio
async def test_validate_skips_when_no_extensions():
    card = {"name": "agent", "capabilities": {}}
    findings = await validate_agent_card(card, store=InMemoryManifestStore())
    assert findings == []


@pytest.mark.asyncio
async def test_validate_unsupported_manifest_version(fake_manifest):
    # Forge a manifest with a future major version.
    payload = fake_manifest.model_dump(by_alias=True)
    payload["manifest_version"] = "2.0.0"
    forged = ExtensionManifest.model_validate(payload)
    store = InMemoryManifestStore({FAKE_URI: forged})
    card = _card_declaring(
        FAKE_URI, {"version": "1.0.0", "endpoint": "https://x"}
    )
    findings = await validate_agent_card(card, store=store)
    assert findings[0].kind == FindingKind.MANIFEST_VERSION_UNSUPPORTED


# --------------------------------------------------------------------------
# LocalManifestStore — exercise the path-mapping convention
# --------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_local_manifest_store_round_trip(tmp_path, fake_manifest):
    path = tmp_path / "example.org" / "fake-protocol" / "v1" / "manifest.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        fake_manifest.model_dump_json(by_alias=True, indent=2, exclude_none=True),
        encoding="utf-8",
    )
    store = LocalManifestStore(tmp_path)
    found = await store.fetch(FAKE_URI)
    assert found is not None
    assert found.extension.uri == FAKE_URI


@pytest.mark.asyncio
async def test_local_manifest_store_returns_none_when_missing(tmp_path):
    store = LocalManifestStore(tmp_path)
    assert await store.fetch(FAKE_URI) is None


# --------------------------------------------------------------------------
# Integration: validate against the manifests published on github.io
# for the four reference protocols (ACAP/Phala/NERVE/PACE). This test
# fetches the live manifests over HTTPS — same path any third-party
# validator would take. Skipped when no network is available.
# --------------------------------------------------------------------------


SHIPPED_MANIFEST_URIS = [
    "https://ravikiran438.github.io/agent-consent-protocol/v1",
    "https://ravikiran438.github.io/phala-protocol/v1",
    "https://ravikiran438.github.io/pratyahara-nerve/v1",
    "https://ravikiran438.github.io/sauvidya-pace/v1",
]


@pytest.mark.parametrize("uri", SHIPPED_MANIFEST_URIS)
def test_shipped_manifest_loads_and_validates(uri):
    import httpx
    manifest_url = uri.rstrip("/") + "/manifest.json"
    try:
        resp = httpx.get(manifest_url, timeout=5.0)
    except (httpx.ConnectError, httpx.TimeoutException) as exc:
        pytest.skip(f"network unavailable: {exc}")
    if resp.status_code != 200:
        pytest.skip(f"manifest not yet published at {manifest_url} ({resp.status_code})")
    raw = json.loads(resp.text)
    manifest = ExtensionManifest.model_validate(raw)
    assert manifest.extension.uri == uri
    assert isinstance(manifest.agent_card_payload_schema, dict)
    assert manifest.agent_card_payload_schema.get("type") == "object"
